server:
  port: 8080
spring:
  dubbo:
    application:
      name: gmall-consumer-user
    registry:
      address: 192.168.183.170:6000
      protocol: zookeeper
    protocol: dubbo
    base-package: com.lby.gmall.user.controller
